version: '3'
services:
  my-sql-compose:
    image: mysql:8.0.33
    container_name: my-sql-compose
    environment:
      - MYSQL_ROOT_PASSWORD=Pastibisa
      - MYSQL_DATABASE=Gin_todo
    ports:
      - 3307:3306
    networks:
      - my-network

  my-app-compose:
    container_name: my-app-compose
    restart: always
    image: todolist
    ports:
      - 8080:8080
    networks:
      - my-network
    depends_on:
      - my-sql-compose
networks:
  my-network:
