package repository

import (
	"github.com/stretchr/testify/mock"
	"todoGin/model/entity"
)

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *MockTodoRepository) GetAll() ([]entity.Todolist, error) {
	ret := _m.Called()

	var r0 []entity.Todolist
	if rf, ok := ret.Get(0).(func() []entity.Todolist); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Todolist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *MockTodoRepository) GetByID(todoID int64) (*entity.Todolist, error) {
	return nil, nil
}

func (_m *MockTodoRepository) Create(title string) (*entity.Todolist, error) {
	return nil, nil
}

func (_m *MockTodoRepository) Update(todoID int64, updates map[string]interface{}) (*entity.Todolist, error) {
	return nil, nil
}

func (_m *MockTodoRepository) Delete(todoID int64) (int64, error) {
	return 0, nil
}

type mockConstructorTestingTNewMockTodoRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTodoRepository(t mockConstructorTestingTNewMockTodoRepository) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
